//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AicAms.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AicAms.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string AcceptedDdl {
            get {
                return ResourceManager.GetString("AcceptedDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string AlertActionTitle {
            get {
                return ResourceManager.GetString("AlertActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string AllDdl {
            get {
                return ResourceManager.GetString("AllDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All employees.
        /// </summary>
        internal static string AllEmpVar {
            get {
                return ResourceManager.GetString("AllEmpVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string ApproveButton {
            get {
                return ResourceManager.GetString("ApproveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will be verified by your current location.
        /// </summary>
        internal static string AttendanceLocationLabel {
            get {
                return ResourceManager.GetString("AttendanceLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or password is incorrect.
        /// </summary>
        internal static string AuthFailMsg {
            get {
                return ResourceManager.GetString("AuthFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Early:.
        /// </summary>
        internal static string BeginEarlyText {
            get {
                return ResourceManager.GetString("BeginEarlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Late:.
        /// </summary>
        internal static string BeginLateText {
            get {
                return ResourceManager.GetString("BeginLateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelToolbar {
            get {
                return ResourceManager.GetString("CancelToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string ChangeLang {
            get {
                return ResourceManager.GetString("ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language will be changed after the application is restarted. Continue?.
        /// </summary>
        internal static string ChangeLangMsg {
            get {
                return ResourceManager.GetString("ChangeLangMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string CharH {
            get {
                return ResourceManager.GetString("CharH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string CharM {
            get {
                return ResourceManager.GetString("CharM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        internal static string CheckedGridTitle {
            get {
                return ResourceManager.GetString("CheckedGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking location.
        /// </summary>
        internal static string CheckingLocationLabel {
            get {
                return ResourceManager.GetString("CheckingLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your Internet connection.
        /// </summary>
        internal static string CheckInternetMsg {
            get {
                return ResourceManager.GetString("CheckInternetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from:.
        /// </summary>
        internal static string DateFromLabel {
            get {
                return ResourceManager.GetString("DateFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DateGridTitle {
            get {
                return ResourceManager.GetString("DateGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to:.
        /// </summary>
        internal static string DateToLabel {
            get {
                return ResourceManager.GetString("DateToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string DayGridTitle {
            get {
                return ResourceManager.GetString("DayGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string DaysText {
            get {
                return ResourceManager.GetString("DaysText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string DaySummaryText {
            get {
                return ResourceManager.GetString("DaySummaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day summary.
        /// </summary>
        internal static string DaySummaryTitle {
            get {
                return ResourceManager.GetString("DaySummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day:.
        /// </summary>
        internal static string DayText {
            get {
                return ResourceManager.GetString("DayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose day.
        /// </summary>
        internal static string DayTitle {
            get {
                return ResourceManager.GetString("DayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Approval.
        /// </summary>
        internal static string DecisionTitle {
            get {
                return ResourceManager.GetString("DecisionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department:.
        /// </summary>
        internal static string DepartmentLabel {
            get {
                return ResourceManager.GetString("DepartmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose department.
        /// </summary>
        internal static string DepartmentTitle {
            get {
                return ResourceManager.GetString("DepartmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string DownloadingText {
            get {
                return ResourceManager.GetString("DownloadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dur..
        /// </summary>
        internal static string DurGridTitle {
            get {
                return ResourceManager.GetString("DurGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp ID.
        /// </summary>
        internal static string EmpIdGridTitle {
            get {
                return ResourceManager.GetString("EmpIdGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID:.
        /// </summary>
        internal static string EmpIdText {
            get {
                return ResourceManager.GetString("EmpIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee:.
        /// </summary>
        internal static string EmployeeLabel {
            get {
                return ResourceManager.GetString("EmployeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose employee.
        /// </summary>
        internal static string EmployeeTitle {
            get {
                return ResourceManager.GetString("EmployeeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuses.
        /// </summary>
        internal static string ExcuseDdl {
            get {
                return ResourceManager.GetString("ExcuseDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse.
        /// </summary>
        internal static string ExcuseStr {
            get {
                return ResourceManager.GetString("ExcuseStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse Request.
        /// </summary>
        internal static string ExcuseTitle {
            get {
                return ResourceManager.GetString("ExcuseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse type:.
        /// </summary>
        internal static string ExcuseTypeLabel {
            get {
                return ResourceManager.GetString("ExcuseTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose excuse type.
        /// </summary>
        internal static string ExcuseTypeTitle {
            get {
                return ResourceManager.GetString("ExcuseTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set Time from &lt; Time to.
        /// </summary>
        internal static string ExcuseValidationError {
            get {
                return ResourceManager.GetString("ExcuseValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request didn&apos;t success, please contact administrator.
        /// </summary>
        internal static string FailureSentRequst {
            get {
                return ResourceManager.GetString("FailureSentRequst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prove you have fingers!.
        /// </summary>
        internal static string FingerprintComponentMsg {
            get {
                return ResourceManager.GetString("FingerprintComponentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string HoursText {
            get {
                return ResourceManager.GetString("HoursText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs.
        /// </summary>
        internal static string HrsText {
            get {
                return ResourceManager.GetString("HrsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string IdGridTitle {
            get {
                return ResourceManager.GetString("IdGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string InfoGridTitle {
            get {
                return ResourceManager.GetString("InfoGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string InGridTitle {
            get {
                return ResourceManager.GetString("InGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Location.
        /// </summary>
        internal static string InLocationGridTitle {
            get {
                return ResourceManager.GetString("InLocationGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButtonTitle {
            get {
                return ResourceManager.GetString("LoginButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string LoginPlaceholder {
            get {
                return ResourceManager.GetString("LoginPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutButtonTitle {
            get {
                return ResourceManager.GetString("LogoutButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutTitle {
            get {
                return ResourceManager.GetString("LogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by time of request:.
        /// </summary>
        internal static string MasterSurpriseLabel {
            get {
                return ResourceManager.GetString("MasterSurpriseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose master surprise.
        /// </summary>
        internal static string MasterSurpriseTitle {
            get {
                return ResourceManager.GetString("MasterSurpriseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string MonthSummaryText {
            get {
                return ResourceManager.GetString("MonthSummaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month summary.
        /// </summary>
        internal static string MonthSummaryTitle {
            get {
                return ResourceManager.GetString("MonthSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month:.
        /// </summary>
        internal static string MonthText {
            get {
                return ResourceManager.GetString("MonthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose month.
        /// </summary>
        internal static string MonthTitle {
            get {
                return ResourceManager.GetString("MonthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set Date from &lt;= Date to.
        /// </summary>
        internal static string MyRequestsValidationError {
            get {
                return ResourceManager.GetString("MyRequestsValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameGridTitle {
            get {
                return ResourceManager.GetString("NameGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient rights to perform this action.
        /// </summary>
        internal static string NoAccessMsg {
            get {
                return ResourceManager.GetString("NoAccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data yet.
        /// </summary>
        internal static string NoDataYet {
            get {
                return ResourceManager.GetString("NoDataYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all fields.
        /// </summary>
        internal static string NotEnouthFields {
            get {
                return ResourceManager.GetString("NotEnouthFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select something.
        /// </summary>
        internal static string NotSelectedError {
            get {
                return ResourceManager.GetString("NotSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Early:.
        /// </summary>
        internal static string OutEarlyText {
            get {
                return ResourceManager.GetString("OutEarlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        internal static string OutGridTitle {
            get {
                return ResourceManager.GetString("OutGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Late:.
        /// </summary>
        internal static string OutLateText {
            get {
                return ResourceManager.GetString("OutLateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch In:.
        /// </summary>
        internal static string PunchInText {
            get {
                return ResourceManager.GetString("PunchInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch Out:.
        /// </summary>
        internal static string PunchOutText {
            get {
                return ResourceManager.GetString("PunchOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason:.
        /// </summary>
        internal static string ReasonLabel {
            get {
                return ResourceManager.GetString("ReasonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string RejectButton {
            get {
                return ResourceManager.GetString("RejectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string RejectedDdl {
            get {
                return ResourceManager.GetString("RejectedDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        internal static string ReqIdText {
            get {
                return ResourceManager.GetString("ReqIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set Date from &lt;= Date to.
        /// </summary>
        internal static string RequestDecisionValidationError {
            get {
                return ResourceManager.GetString("RequestDecisionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Surprise.
        /// </summary>
        internal static string RequestSurpriseTitle {
            get {
                return ResourceManager.GetString("RequestSurpriseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My requests.
        /// </summary>
        internal static string RequestTitle {
            get {
                return ResourceManager.GetString("RequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request type:.
        /// </summary>
        internal static string RequestTypeLable {
            get {
                return ResourceManager.GetString("RequestTypeLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose request type.
        /// </summary>
        internal static string RequestTypeTitle {
            get {
                return ResourceManager.GetString("RequestTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send again.
        /// </summary>
        internal static string ResendPushButton {
            get {
                return ResourceManager.GetString("ResendPushButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart app.
        /// </summary>
        internal static string RestartApp {
            get {
                return ResourceManager.GetString("RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string RetGridTitle {
            get {
                return ResourceManager.GetString("RetGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request type:.
        /// </summary>
        internal static string RetIdText {
            get {
                return ResourceManager.GetString("RetIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending request.
        /// </summary>
        internal static string SendingRequestLabel {
            get {
                return ResourceManager.GetString("SendingRequestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send surprise.
        /// </summary>
        internal static string SendSurpriseButton {
            get {
                return ResourceManager.GetString("SendSurpriseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Duration:.
        /// </summary>
        internal static string ShiftDurationText {
            get {
                return ResourceManager.GetString("ShiftDurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift:.
        /// </summary>
        internal static string ShiftText {
            get {
                return ResourceManager.GetString("ShiftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose shift.
        /// </summary>
        internal static string ShiftTitle {
            get {
                return ResourceManager.GetString("ShiftTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string ShowButton {
            get {
                return ResourceManager.GetString("ShowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        internal static string StatusA {
            get {
                return ResourceManager.GetString("StatusA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandate.
        /// </summary>
        internal static string StatusCM {
            get {
                return ResourceManager.GetString("StatusCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string StatusDashboard {
            get {
                return ResourceManager.GetString("StatusDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusGridTitle {
            get {
                return ResourceManager.GetString("StatusGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holday.
        /// </summary>
        internal static string StatusH {
            get {
                return ResourceManager.GetString("StatusH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN Only.
        /// </summary>
        internal static string StatusIN {
            get {
                return ResourceManager.GetString("StatusIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joborder.
        /// </summary>
        internal static string StatusJB {
            get {
                return ResourceManager.GetString("StatusJB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT-IN.
        /// </summary>
        internal static string StatusOI {
            get {
                return ResourceManager.GetString("StatusOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT Only.
        /// </summary>
        internal static string StatusOU {
            get {
                return ResourceManager.GetString("StatusOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onwork.
        /// </summary>
        internal static string StatusP {
            get {
                return ResourceManager.GetString("StatusP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed vacation.
        /// </summary>
        internal static string StatusPE {
            get {
                return ResourceManager.GetString("StatusPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string StatusText {
            get {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose status.
        /// </summary>
        internal static string StatusTitle {
            get {
                return ResourceManager.GetString("StatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid vacation.
        /// </summary>
        internal static string StatusUE {
            get {
                return ResourceManager.GetString("StatusUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string StatusUnknown {
            get {
                return ResourceManager.GetString("StatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        internal static string StatusWE {
            get {
                return ResourceManager.GetString("StatusWE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request sent successfully.
        /// </summary>
        internal static string SuccessSentRequest {
            get {
                return ResourceManager.GetString("SuccessSentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessText {
            get {
                return ResourceManager.GetString("SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary:.
        /// </summary>
        internal static string SummaryTypeLabel {
            get {
                return ResourceManager.GetString("SummaryTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose summary type.
        /// </summary>
        internal static string SummaryTypeTitle {
            get {
                return ResourceManager.GetString("SummaryTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surprise Attendance.
        /// </summary>
        internal static string SurpriseAccomplishTitle {
            get {
                return ResourceManager.GetString("SurpriseAccomplishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surprise Results.
        /// </summary>
        internal static string SurpriseResultTitle {
            get {
                return ResourceManager.GetString("SurpriseResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time from:.
        /// </summary>
        internal static string TimeFromLabel {
            get {
                return ResourceManager.GetString("TimeFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to:.
        /// </summary>
        internal static string TimeToLabel {
            get {
                return ResourceManager.GetString("TimeToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total absent days:.
        /// </summary>
        internal static string TotalAbsentDays {
            get {
                return ResourceManager.GetString("TotalAbsentDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total gap duration without excuse.
        /// </summary>
        internal static string TotalGapDurationWithoutExcuse {
            get {
                return ResourceManager.GetString("TotalGapDurationWithoutExcuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total late hours:.
        /// </summary>
        internal static string TotalLateHours {
            get {
                return ResourceManager.GetString("TotalLateHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total shift duration.
        /// </summary>
        internal static string TotalShiftDuration {
            get {
                return ResourceManager.GetString("TotalShiftDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total work duration.
        /// </summary>
        internal static string TotalWorkDuration {
            get {
                return ResourceManager.GetString("TotalWorkDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total working hours:.
        /// </summary>
        internal static string TotalWorkingHours {
            get {
                return ResourceManager.GetString("TotalWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeGridTitle {
            get {
                return ResourceManager.GetString("TypeGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string TypeText {
            get {
                return ResourceManager.GetString("TypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get location.
        /// </summary>
        internal static string UnableLocationMessage {
            get {
                return ResourceManager.GetString("UnableLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under process.
        /// </summary>
        internal static string UnderProcessDdl {
            get {
                return ResourceManager.GetString("UnderProcessDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string UserGridTitle {
            get {
                return ResourceManager.GetString("UserGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login:.
        /// </summary>
        internal static string UserText {
            get {
                return ResourceManager.GetString("UserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation.
        /// </summary>
        internal static string VacationStr {
            get {
                return ResourceManager.GetString("VacationStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation Request.
        /// </summary>
        internal static string VacationTitle {
            get {
                return ResourceManager.GetString("VacationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation type:.
        /// </summary>
        internal static string VacationTypeLabel {
            get {
                return ResourceManager.GetString("VacationTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose vacation type.
        /// </summary>
        internal static string VacationTypeTitle {
            get {
                return ResourceManager.GetString("VacationTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set Date from &lt; Date to.
        /// </summary>
        internal static string VacationValidationError {
            get {
                return ResourceManager.GetString("VacationValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacations.
        /// </summary>
        internal static string VacDdl {
            get {
                return ResourceManager.GetString("VacDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, .
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Duration:.
        /// </summary>
        internal static string WorkDurationText {
            get {
                return ResourceManager.GetString("WorkDurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        internal static string YearText {
            get {
                return ResourceManager.GetString("YearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose year.
        /// </summary>
        internal static string YearTitle {
            get {
                return ResourceManager.GetString("YearTitle", resourceCulture);
            }
        }
    }
}
